name: Build app
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Get Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 -d > app/release.keystore

      - name: Build
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          chmod +x gradlew
          ./gradlew build
          ls app/build/outputs/apk/release

      - name: Move and rename apk
        run: |
          ls app/build/outputs/apk/release
          mv app/build/outputs/apk/release/app-release.apk app/CrashInteface.apk
          ls app
          pwd

      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: "crash-interface"
          path: app/CrashInterface.apk
        run: pwd
      

